language: node_js

node_js:
  - 9
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules

install:
  - yarn install

script:
  - echo $TRAVIS_BRANCH | sed -E 's/([^\/]+)\/(.*$)/\2.\1-react-sep.surge.sh/g'
  - yarn build

after_success:
  - surge --project ./build --domain test-homework.surge.sh
