language: node_js

node_js:
  - 9
cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install

before_script:
  - yarn start -- --silent &

script:
  - yarn build
  - echo TRAVIS_BUILD_ID
  - echo $TRAVIS_BUILD_ID
  - echo TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo TRAVIS_PULL_REQUEST_SLUG
  - echo $TRAVIS_PULL_REQUEST_SLUG
  - echo TRAVIS_REPO_SLUG
  - echo $TRAVIS_REPO_SLUG

after_success:
  - surge --project ./build --domain test-homework.surge.sh
