language: node_js

node_js:
  - 9
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules

install:
  - yarn install

script:
  - echo $TRAVIS_BUILD_ID
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_PULL_REQUEST_SLUG
  - echo $TRAVIS_REPO_SLUG
  - yarn build

after_success:
  - surge --project ./build --domain test-homework.surge.sh
